---
dotfiles_user_email_work: "dfarrell@redhat.com"
dotfiles_user_email_personal: "dfarrell07@gmail.com"
dotfiles_user_name: "Daniel Farrell"
dotfiles_github_user: "dfarrell07"

dotfiles_oh_my_zsh_theme: gallois
dotfiles_oh_my_zsh_plugins:
  - git
  - python
  - history-substring-search

dotfiles_aws_profile: "aws-acm-subm"

dotfiles_tmux_prefix: "C-a"
dotfiles_tmux_history_limit: 50000

dotfiles_internal_git_host: ""
