---
driver:
  name: podman

lint: |
  set -e
  ansible-lint --profile production .

platforms:
  - name: instance
    image: ghcr.io/geerlingguy/docker-fedora44-ansible:latest
    pre_build_image: true
    privileged: true
    override_command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rshared
    cgroupns_mode: private
    networks:
      - name: default

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  lint: ansible-lint
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections:~/.ansible/collections:/usr/share/ansible/collections
    ANSIBLE_LIBRARY: ''
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections:~/.ansible/collections:/usr/share/ansible/collections
      gathering: smart
