---
driver:
  name: podman

platforms:
  - name: fedora-test
    # To update digest: podman pull docker.io/geerlingguy/docker-fedora43-ansible:latest
    # then: podman inspect --format='{{.Digest}}' docker.io/geerlingguy/docker-fedora43-ansible:latest
    image: docker.io/geerlingguy/docker-fedora43-ansible@sha256:ba40b870c4930565910e4917dfc41b9e022d2387c93b45abb0b482a23ba91c48
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections:~/.ansible/collections:/usr/share/ansible/collections
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
