---
driver:
  name: podman

platforms:
  - name: fedora-test
    image: docker.io/geerlingguy/docker-fedora42-ansible:latest
    privileged: true
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: /dev/null
  config_options:
    defaults:
      vault_password_file: /dev/null

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
