---
desktop_environment: auto  # auto, sway, i3, gnome

desktop_sway_packages:
  - sway
  - swayidle
  - swaylock
  - wofi
  - grim
  - slurp
  - brightnessctl

desktop_i3_packages:
  - i3
  - i3status-rust
  - i3lock
  - dmenu
  - xss-lock
  - autorandr

desktop_common_packages:
  - alacritty
  - gvim
  - dejavu-sans-mono-fonts
  - terminus-fonts
