---
notes_repo_path: "{{ ansible_user_dir }}/notes"
notes_remote_url: "git@github.com:{{ dotfiles_github_user }}/notes.git"
notes_remote_url_https: "https://github.com/{{ dotfiles_github_user }}/notes.git"
notes_transcrypt_cipher: aes-256-cbc
