---
# roles/dotfiles/handlers/main.yml

- name: Restart ssh-agent
  ansible.builtin.systemd:
    name: ssh-agent
    scope: user
    state: restarted
    daemon_reload: true
  when: ansible_facts['virtualization_type'] | default('') not in ['container', 'docker', 'podman']
  failed_when: false
