---
driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: fedora-test
    box: fedora/43-cloud-base
    memory: 4096
    cpus: 2

provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections:~/.ansible/collections:/usr/share/ansible/collections
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
    privilege_escalation:
      become: true

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
