---
containers_auth_file: "{{ ansible_facts['user_dir'] }}/.config/containers/auth.json"

containers_config_dir: "{{ ansible_facts['user_dir'] }}/.config/containers"

# kind host prerequisites (OVN-K/Submariner testing)
containers_kind_log_driver: "k8s-file"
containers_kind_pids_limit: 65536
containers_kind_nofile_limit: 65536
containers_kind_nofile_hard_limit: 524288
