---
containers_auth_file: "{{ ansible_user_dir }}/.config/containers/auth.json"

containers_registries:
  - registry.redhat.io
  - quay.io

containers_config_dir: "{{ ansible_user_dir }}/.config/containers"

# kind host prerequisites (OVN-K/Submariner testing)
containers_kind_log_driver: "k8s-file"
containers_kind_pids_limit: 65536
