---
driver:
  name: podman

platforms:
  - name: debian-test
    # To update digest: podman pull docker.io/geerlingguy/docker-debian13-ansible:latest
    # then: podman inspect --format='{{.Digest}}' docker.io/geerlingguy/docker-debian13-ansible:latest
    image: docker.io/geerlingguy/docker-debian13-ansible@sha256:891cb61fdefb4956ba0d0fb13b439749a0cb4b5c65d63b6824d0f97d1b9a0765
    pre_build_image: true
    privileged: true
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_VAULT_PASSWORD_FILE: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
    ANSIBLE_COLLECTIONS_PATH: ${MOLECULE_PROJECT_DIRECTORY}/collections:~/.ansible/collections:/usr/share/ansible/collections
  config_options:
    defaults:
      vault_password_file: ${MOLECULE_PROJECT_DIRECTORY}/scripts/vault-pass-ci.sh
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/collections:~/.ansible/collections:/usr/share/ansible/collections
      gathering: smart

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify
    - destroy
