---
redhat_ca_certs:
  - 2022-IT-Root-CA.pem
  - Eng-CA.crt

redhat_ca_dest: /etc/pki/ca-trust/source/anchors

redhat_vpn_packages:
  - redhat-internal-openvpn-profiles

redhat_cert_packages:
  - redhat-internal-cert-install
